# Generated by Django 5.0.3 on 2024-04-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='beadás',
            fields=[
                ('lock_in_time', models.DateTimeField()),
                ('beadási_határidő', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'beadás',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('beosztás', models.CharField(max_length=45)),
                ('beadási_határidő', models.DateTimeField()),
                ('név', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'person',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='munkakör',
            fields=[
                ('beosztás', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('pénz', models.IntegerField()),
            ],
            options={
                'db_table': 'munkakör',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ember',
            fields=[
                ('név', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('jelszó', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ember',
                'managed': True,
            },
        ),
    ]
